# Introduction

El presente documento tiene el objetivo de presentar una propuesta teórica y metodológica de medición de la cohesión social en Chile, utilizando los datos del estudio longitudinal [ELSOC](https://coes.cl/encuesta-panel/). Esta propuesta pretende servir, a corto plazo, de insumo para el [segundo foro de cohesión social](añadir link cuando exista) en conjunto con el [Centro de Estudios Públicos](https://www.cepchile.cl/), mientras que el objetivo a largo plazo es que pueda ser un sustento para el futuro visualizador del [Observatorio de Cohesión Social](https://ocs-coes.com/). Considerando lo anterior, en un primer momento este trabajo se dedicará a profundizar en la dimensión horizontal de la cohesión social, y posteriormente se elaborará el apartado correspondiente a la dimensión vertical. 

::: {.hidden}
Cambiar el link del OCS al visualizador cuando esté listo
:::

El [Centro de Estudios de Conflicto y Cohesión Social](https://coes.cl/) (COES) es una iniciativa que nace el año 2014 con la intención de estudiar desde una perspectiva multidimensional los factores que agudizan el conflicto social y aquellos que fortalecen la cohesión social en Chile. COES se presenta como un centro que busca el vínculo entre ciencia, Estado y sociedad, proponiendo diagnósticos y soluciones que contribuyan al desarrollo y bienestar del país.

A partir de la necesidad de generar evidencia empírica sobre cohesión social, desde COES surge el Observatorio de Cohesión Social, un espacio de investigación orientado al análisis de datos mediante la generación de herramientas metodológicas actualizadas y pertinentes. El OCS busca poner a disposición pública los hallazgos provenientes tanto de encuestas nacionales como de comparativa internacional con tal de profundizar en las dinámicas circunscritas en la cohesión social. 

La construcción de este nuevo marco de medición tomará como referencia la [propuesta de medición de cohesión social en Chile con ELSOC](https://ocscoes.github.io/cohesion-elsoc/), así como la [propuesta de medición de cohesión social en América Latina con LAPOP](https://ocs-coes.com/reportes/posts/2025_reportes_tecnico/), en orden de elaborar un insumo que permita comprender y profundizar en los factores asociados a la cohesión social en Chile. El primer trabajo mencionado es uno de los antecedentes principales del actual trabajo, puesto que, a partir de una revisión sistemática de estudios internacionales, busca identificar los principales indicadores que posibilitan la operacionalización y medición de la cohesión social en Chile con los datos de ELSOC. El segundo documento pretende aportar en la medición de la cohesión social pero a un nivel regional, abordando la construcción técnica y metodológica para medir este fenómeno en América Latina. 

El desarrollo de este documento estará guiado por tres secciones principales. Primero, la presentación de las dos propuestas ya mencionadas, discutiendo sus principales similitudes y diferencias, en vista de rescatar los mayores aportes de cada una. Posteriormente, se dará a conocer la nueva propuesta junto con la operacionalización de sus subdimensiones. En segundo lugar, se presentarán los análisis de fiabilidad métrica de los constructos propuestos, pasando por un Análisis Factorial Exploratorio a modo de diagnóstico, y luego un Análisis Factorial Confirmatorio para validar los factores. Por último, se visualizarán las asociaciones de los constructos con indicadores de migración, buscando capturar relaciones transversales y longitudinales entre la cohesión social y las opinión pública de las personas respecto a la migración.